/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameJoinRouteImport } from './routes/game.join'
import { Route as GameCreateRouteImport } from './routes/game.create'
import { Route as GameRoomCodeRouteImport } from './routes/game.$roomCode'
import { Route as DisplayRoomCodeRouteImport } from './routes/display.$roomCode'
import { Route as ApiSeedRouteImport } from './routes/api.seed'
import { Route as GameRoomCodeResultsRouteImport } from './routes/game.$roomCode.results'
import { Route as GameRoomCodePlayRouteImport } from './routes/game.$roomCode.play'
import { Route as ApiGamesJoinRouteImport } from './routes/api.games.join'
import { Route as ApiGamesCreateRouteImport } from './routes/api.games.create'
import { Route as ApiGamesRoomCodeRouteImport } from './routes/api.games.$roomCode'
import { Route as ApiGamesRoomCodeStartRouteImport } from './routes/api.games.$roomCode.start'
import { Route as ApiGamesRoomCodeResultsRouteImport } from './routes/api.games.$roomCode.results'
import { Route as ApiGamesRoomCodeQuestionRouteImport } from './routes/api.games.$roomCode.question'
import { Route as ApiGamesRoomCodeNextGameRouteImport } from './routes/api.games.$roomCode.next-game'
import { Route as ApiGamesRoomCodeAnswerRouteImport } from './routes/api.games.$roomCode.answer'

const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameJoinRoute = GameJoinRouteImport.update({
  id: '/game/join',
  path: '/game/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCreateRoute = GameCreateRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomCodeRoute = GameRoomCodeRouteImport.update({
  id: '/game/$roomCode',
  path: '/game/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoomCodeRoute = DisplayRoomCodeRouteImport.update({
  id: '/$roomCode',
  path: '/$roomCode',
  getParentRoute: () => DisplayRoute,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomCodeResultsRoute = GameRoomCodeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => GameRoomCodeRoute,
} as any)
const GameRoomCodePlayRoute = GameRoomCodePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GameRoomCodeRoute,
} as any)
const ApiGamesJoinRoute = ApiGamesJoinRouteImport.update({
  id: '/api/games/join',
  path: '/api/games/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesCreateRoute = ApiGamesCreateRouteImport.update({
  id: '/api/games/create',
  path: '/api/games/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoomCodeRoute = ApiGamesRoomCodeRouteImport.update({
  id: '/api/games/$roomCode',
  path: '/api/games/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoomCodeStartRoute = ApiGamesRoomCodeStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiGamesRoomCodeRoute,
} as any)
const ApiGamesRoomCodeResultsRoute = ApiGamesRoomCodeResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiGamesRoomCodeRoute,
} as any)
const ApiGamesRoomCodeQuestionRoute =
  ApiGamesRoomCodeQuestionRouteImport.update({
    id: '/question',
    path: '/question',
    getParentRoute: () => ApiGamesRoomCodeRoute,
  } as any)
const ApiGamesRoomCodeNextGameRoute =
  ApiGamesRoomCodeNextGameRouteImport.update({
    id: '/next-game',
    path: '/next-game',
    getParentRoute: () => ApiGamesRoomCodeRoute,
  } as any)
const ApiGamesRoomCodeAnswerRoute = ApiGamesRoomCodeAnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => ApiGamesRoomCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/display': typeof DisplayRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/display/$roomCode': typeof DisplayRoomCodeRoute
  '/game/$roomCode': typeof GameRoomCodeRouteWithChildren
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/games/$roomCode': typeof ApiGamesRoomCodeRouteWithChildren
  '/api/games/create': typeof ApiGamesCreateRoute
  '/api/games/join': typeof ApiGamesJoinRoute
  '/game/$roomCode/play': typeof GameRoomCodePlayRoute
  '/game/$roomCode/results': typeof GameRoomCodeResultsRoute
  '/api/games/$roomCode/answer': typeof ApiGamesRoomCodeAnswerRoute
  '/api/games/$roomCode/next-game': typeof ApiGamesRoomCodeNextGameRoute
  '/api/games/$roomCode/question': typeof ApiGamesRoomCodeQuestionRoute
  '/api/games/$roomCode/results': typeof ApiGamesRoomCodeResultsRoute
  '/api/games/$roomCode/start': typeof ApiGamesRoomCodeStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display': typeof DisplayRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/display/$roomCode': typeof DisplayRoomCodeRoute
  '/game/$roomCode': typeof GameRoomCodeRouteWithChildren
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/games/$roomCode': typeof ApiGamesRoomCodeRouteWithChildren
  '/api/games/create': typeof ApiGamesCreateRoute
  '/api/games/join': typeof ApiGamesJoinRoute
  '/game/$roomCode/play': typeof GameRoomCodePlayRoute
  '/game/$roomCode/results': typeof GameRoomCodeResultsRoute
  '/api/games/$roomCode/answer': typeof ApiGamesRoomCodeAnswerRoute
  '/api/games/$roomCode/next-game': typeof ApiGamesRoomCodeNextGameRoute
  '/api/games/$roomCode/question': typeof ApiGamesRoomCodeQuestionRoute
  '/api/games/$roomCode/results': typeof ApiGamesRoomCodeResultsRoute
  '/api/games/$roomCode/start': typeof ApiGamesRoomCodeStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/display': typeof DisplayRouteWithChildren
  '/api/seed': typeof ApiSeedRoute
  '/display/$roomCode': typeof DisplayRoomCodeRoute
  '/game/$roomCode': typeof GameRoomCodeRouteWithChildren
  '/game/create': typeof GameCreateRoute
  '/game/join': typeof GameJoinRoute
  '/api/games/$roomCode': typeof ApiGamesRoomCodeRouteWithChildren
  '/api/games/create': typeof ApiGamesCreateRoute
  '/api/games/join': typeof ApiGamesJoinRoute
  '/game/$roomCode/play': typeof GameRoomCodePlayRoute
  '/game/$roomCode/results': typeof GameRoomCodeResultsRoute
  '/api/games/$roomCode/answer': typeof ApiGamesRoomCodeAnswerRoute
  '/api/games/$roomCode/next-game': typeof ApiGamesRoomCodeNextGameRoute
  '/api/games/$roomCode/question': typeof ApiGamesRoomCodeQuestionRoute
  '/api/games/$roomCode/results': typeof ApiGamesRoomCodeResultsRoute
  '/api/games/$roomCode/start': typeof ApiGamesRoomCodeStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/display'
    | '/api/seed'
    | '/display/$roomCode'
    | '/game/$roomCode'
    | '/game/create'
    | '/game/join'
    | '/api/games/$roomCode'
    | '/api/games/create'
    | '/api/games/join'
    | '/game/$roomCode/play'
    | '/game/$roomCode/results'
    | '/api/games/$roomCode/answer'
    | '/api/games/$roomCode/next-game'
    | '/api/games/$roomCode/question'
    | '/api/games/$roomCode/results'
    | '/api/games/$roomCode/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/display'
    | '/api/seed'
    | '/display/$roomCode'
    | '/game/$roomCode'
    | '/game/create'
    | '/game/join'
    | '/api/games/$roomCode'
    | '/api/games/create'
    | '/api/games/join'
    | '/game/$roomCode/play'
    | '/game/$roomCode/results'
    | '/api/games/$roomCode/answer'
    | '/api/games/$roomCode/next-game'
    | '/api/games/$roomCode/question'
    | '/api/games/$roomCode/results'
    | '/api/games/$roomCode/start'
  id:
    | '__root__'
    | '/'
    | '/display'
    | '/api/seed'
    | '/display/$roomCode'
    | '/game/$roomCode'
    | '/game/create'
    | '/game/join'
    | '/api/games/$roomCode'
    | '/api/games/create'
    | '/api/games/join'
    | '/game/$roomCode/play'
    | '/game/$roomCode/results'
    | '/api/games/$roomCode/answer'
    | '/api/games/$roomCode/next-game'
    | '/api/games/$roomCode/question'
    | '/api/games/$roomCode/results'
    | '/api/games/$roomCode/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisplayRoute: typeof DisplayRouteWithChildren
  ApiSeedRoute: typeof ApiSeedRoute
  GameRoomCodeRoute: typeof GameRoomCodeRouteWithChildren
  GameCreateRoute: typeof GameCreateRoute
  GameJoinRoute: typeof GameJoinRoute
  ApiGamesRoomCodeRoute: typeof ApiGamesRoomCodeRouteWithChildren
  ApiGamesCreateRoute: typeof ApiGamesCreateRoute
  ApiGamesJoinRoute: typeof ApiGamesJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/join': {
      id: '/game/join'
      path: '/game/join'
      fullPath: '/game/join'
      preLoaderRoute: typeof GameJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/create': {
      id: '/game/create'
      path: '/game/create'
      fullPath: '/game/create'
      preLoaderRoute: typeof GameCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomCode': {
      id: '/game/$roomCode'
      path: '/game/$roomCode'
      fullPath: '/game/$roomCode'
      preLoaderRoute: typeof GameRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$roomCode': {
      id: '/display/$roomCode'
      path: '/$roomCode'
      fullPath: '/display/$roomCode'
      preLoaderRoute: typeof DisplayRoomCodeRouteImport
      parentRoute: typeof DisplayRoute
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomCode/results': {
      id: '/game/$roomCode/results'
      path: '/results'
      fullPath: '/game/$roomCode/results'
      preLoaderRoute: typeof GameRoomCodeResultsRouteImport
      parentRoute: typeof GameRoomCodeRoute
    }
    '/game/$roomCode/play': {
      id: '/game/$roomCode/play'
      path: '/play'
      fullPath: '/game/$roomCode/play'
      preLoaderRoute: typeof GameRoomCodePlayRouteImport
      parentRoute: typeof GameRoomCodeRoute
    }
    '/api/games/join': {
      id: '/api/games/join'
      path: '/api/games/join'
      fullPath: '/api/games/join'
      preLoaderRoute: typeof ApiGamesJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/create': {
      id: '/api/games/create'
      path: '/api/games/create'
      fullPath: '/api/games/create'
      preLoaderRoute: typeof ApiGamesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$roomCode': {
      id: '/api/games/$roomCode'
      path: '/api/games/$roomCode'
      fullPath: '/api/games/$roomCode'
      preLoaderRoute: typeof ApiGamesRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$roomCode/start': {
      id: '/api/games/$roomCode/start'
      path: '/start'
      fullPath: '/api/games/$roomCode/start'
      preLoaderRoute: typeof ApiGamesRoomCodeStartRouteImport
      parentRoute: typeof ApiGamesRoomCodeRoute
    }
    '/api/games/$roomCode/results': {
      id: '/api/games/$roomCode/results'
      path: '/results'
      fullPath: '/api/games/$roomCode/results'
      preLoaderRoute: typeof ApiGamesRoomCodeResultsRouteImport
      parentRoute: typeof ApiGamesRoomCodeRoute
    }
    '/api/games/$roomCode/question': {
      id: '/api/games/$roomCode/question'
      path: '/question'
      fullPath: '/api/games/$roomCode/question'
      preLoaderRoute: typeof ApiGamesRoomCodeQuestionRouteImport
      parentRoute: typeof ApiGamesRoomCodeRoute
    }
    '/api/games/$roomCode/next-game': {
      id: '/api/games/$roomCode/next-game'
      path: '/next-game'
      fullPath: '/api/games/$roomCode/next-game'
      preLoaderRoute: typeof ApiGamesRoomCodeNextGameRouteImport
      parentRoute: typeof ApiGamesRoomCodeRoute
    }
    '/api/games/$roomCode/answer': {
      id: '/api/games/$roomCode/answer'
      path: '/answer'
      fullPath: '/api/games/$roomCode/answer'
      preLoaderRoute: typeof ApiGamesRoomCodeAnswerRouteImport
      parentRoute: typeof ApiGamesRoomCodeRoute
    }
  }
}

interface DisplayRouteChildren {
  DisplayRoomCodeRoute: typeof DisplayRoomCodeRoute
}

const DisplayRouteChildren: DisplayRouteChildren = {
  DisplayRoomCodeRoute: DisplayRoomCodeRoute,
}

const DisplayRouteWithChildren =
  DisplayRoute._addFileChildren(DisplayRouteChildren)

interface GameRoomCodeRouteChildren {
  GameRoomCodePlayRoute: typeof GameRoomCodePlayRoute
  GameRoomCodeResultsRoute: typeof GameRoomCodeResultsRoute
}

const GameRoomCodeRouteChildren: GameRoomCodeRouteChildren = {
  GameRoomCodePlayRoute: GameRoomCodePlayRoute,
  GameRoomCodeResultsRoute: GameRoomCodeResultsRoute,
}

const GameRoomCodeRouteWithChildren = GameRoomCodeRoute._addFileChildren(
  GameRoomCodeRouteChildren,
)

interface ApiGamesRoomCodeRouteChildren {
  ApiGamesRoomCodeAnswerRoute: typeof ApiGamesRoomCodeAnswerRoute
  ApiGamesRoomCodeNextGameRoute: typeof ApiGamesRoomCodeNextGameRoute
  ApiGamesRoomCodeQuestionRoute: typeof ApiGamesRoomCodeQuestionRoute
  ApiGamesRoomCodeResultsRoute: typeof ApiGamesRoomCodeResultsRoute
  ApiGamesRoomCodeStartRoute: typeof ApiGamesRoomCodeStartRoute
}

const ApiGamesRoomCodeRouteChildren: ApiGamesRoomCodeRouteChildren = {
  ApiGamesRoomCodeAnswerRoute: ApiGamesRoomCodeAnswerRoute,
  ApiGamesRoomCodeNextGameRoute: ApiGamesRoomCodeNextGameRoute,
  ApiGamesRoomCodeQuestionRoute: ApiGamesRoomCodeQuestionRoute,
  ApiGamesRoomCodeResultsRoute: ApiGamesRoomCodeResultsRoute,
  ApiGamesRoomCodeStartRoute: ApiGamesRoomCodeStartRoute,
}

const ApiGamesRoomCodeRouteWithChildren =
  ApiGamesRoomCodeRoute._addFileChildren(ApiGamesRoomCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisplayRoute: DisplayRouteWithChildren,
  ApiSeedRoute: ApiSeedRoute,
  GameRoomCodeRoute: GameRoomCodeRouteWithChildren,
  GameCreateRoute: GameCreateRoute,
  GameJoinRoute: GameJoinRoute,
  ApiGamesRoomCodeRoute: ApiGamesRoomCodeRouteWithChildren,
  ApiGamesCreateRoute: ApiGamesCreateRoute,
  ApiGamesJoinRoute: ApiGamesJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
